spring:
  application:
    name: apollo-adminservice
  profiles:
    active: ${apollo_profile}

  datasource:
    url: jdbc:mysql://${mysql_host}:${mysql_port:3306}/${mysql_name}?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
    username: ${mysql_username}
    password: ${mysql_password}

ctrip:
  appid: 100003172
  
server:
  port: 8090
  
logging:
  file: logs/apollo-adminservice.log
