spring:
  application:
    name: apollo-configservice
  profiles:
    active: ${apollo_profile}

  datasource:
    url: jdbc:mysql://${mysql_host}:${mysql_port:3306}/${mysql_name}?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
    username: ${mysql_username}
    password: ${mysql_password}

ctrip:
  appid: 100003171
  
server:
  port: 8080

logging:
  file: logs/apollo-configservice.log
